Task 18
SonyaOrlova/ROR-basic-Test-Guru pull request #21
Opened 2020-11-12 18:36 UTC by SonyaOrlova

2020-11-13 07:33 UTC, BubuntuClu requested changes

2020-11-13 07:33 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    current_user.badges.push(@badges) if @badges.present?
вручение бейджей пользователю может сам сервис делать

2020-11-13 07:33 UTC, BubuntuClu commented on app/models/badge.rb
> +  class << self
логику по выдаче бейджей не должна реализовывать модель. нужно сделать сервис сделать, который будет этим заниматься. если всю логику помещать в модели, то они будут быстро "распухать" и будет нереально в код разбираться

2020-11-13 07:33 UTC, BubuntuClu commented on app/models/badge.rb
> +      @uniq_passed_tests.select { |t| t.category == category }.count == Test.where(category: category).count
давай запросы эти сделаем без рубишного кода, а чистыми скл-запросом.

2020-11-13 07:33 UTC, BubuntuClu commented on app/models/badge.rb
> +      @uniq_passed_tests.select { |t| t.level == level.to_i }.count == Test.where(level: level).count
от select избавляемся, переходим на чистый запрос

2020-11-13 07:33 UTC, BubuntuClu commented on app/models/badge.rb
> +      tries_count = @passed_tests.select { |t| t.title == @passed_test.title && t.level == @passed_test.level }.count
от select избавляемся, переходим на чистый запрос

2020-11-14 18:09 UTC, BubuntuClu requested changes

2020-11-14 18:09 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  has_many :badges, dependent: :destroy
для чего идет привязка бейджей к какому-либо прохождению?

2020-11-14 18:09 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    return if !@test_passage.passed || @test_passage.badges.present?
один тест пассадж не может же быть несколько раз попасть в сервис выдачи тестов. для чего эта проверка?

2020-11-14 18:09 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    @passed_tests.joins(:category).where(categories: { title: category }).select(:title, :level).distinct.size == Test.joins(:category).where(categories: { title: category }).size
`select(:title, :level)` эта опция тут для чего?

2020-11-14 18:09 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    tries_count = @passed_tests.select { |t| t.title == @passed_test.title && t.level == @passed_test.level }.size
тут не заменила рубишный метод на скл запрос

2020-11-14 20:21 UTC, SonyaOrlova commented on app/models/test_passage.rb
> +  has_many :badges, dependent: :destroy
привет! это сделано для того, что я физически могу обновлять страницу /result и каждый раз выдаются баджы, то есть тебе ничто не мешает взять и по урлу зайти на прохождение теста или его результат, просто наткнулась на это и решила привязать к конкретному прохождению

2020-11-14 20:21 UTC, SonyaOrlova commented on app/services/badge_service.rb
> +    return if !@test_passage.passed || @test_passage.badges.present?
это в продолжение из коммента выше

2020-11-14 20:22 UTC, SonyaOrlova commented on app/services/badge_service.rb
> +    tries_count = @passed_tests.select { |t| t.title == @passed_test.title && t.level == @passed_test.level }.size
оу, что-то не запушилось, поправлю

2020-11-14 20:28 UTC, SonyaOrlova commented on app/services/badge_service.rb
> +    @passed_tests.joins(:category).where(categories: { title: category }).select(:title, :level).distinct.size == Test.joins(:category).where(categories: { title: category }).size
это выборка для уникальности тестов, ты же можешь один и тот же тест проходить сколько угодно раз, соответственно я тут беру `все пройденные тесты.в нужной категории.убираю дубликаты по прохождениям одного и того же теста(=select + distinct)`

2020-11-15 07:04 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  has_many :badges, dependent: :destroy
по этому стоит делать выдачу наград не на странице результата, а в методе show, перед тем как сделать редирект

2020-11-15 12:11 UTC, merged